name: MakeCode Arcade Release

on: 
  release:
    types:
      - created
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: install node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: install makecode
        run: |
          npm install -g pxt
          pxt target arcade
      - name: build js
        run: |
          pxt clean
          pxt install
          pxt build --cloud
      - name: build D51
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
          cp ./built/binary.uf2 binary-d51.uf2
      - name: build F4
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
          cp ./built/binary.uf2 binary-f4.uf2
      - name: build P0
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw rpi
          pxt build --hw rpi --cloud
          cp ./built/binary.uf2 binary-p0.uf2
      - name: bundle all
        run: |
          cat binary-*.uf2 > built/arcade.uf2
      - name: upload bundled
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./built/arcade.uf2
          asset_name: arcade.uf2
          asset_content_type: application/octet-stream